export const LISTA_CARGO = [
  {
    value: "COORDINACIÓN DE ÁREA DE TECNOLOGÍAS DE LA INFORMACIÓN",
    text: "COORDINACIÓN DE ÁREA DE TECNOLOGÍAS DE LA INFORMACIÓN",
  },
  {
    value: "ASISTENTE DE LA COORDINACIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN",
    text: "ASISTENTE DE LA COORDINACIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN",
  },
  {
    value: "ASISTENTE DE LA SUBDIRECCIÓN DE INFORMÁTICA Y ESTADÍSTICA",
    text: "ASISTENTE DE LA SUBDIRECCIÓN DE INFORMÁTICA Y ESTADÍSTICA",
  },
  { value: "ESTADÍSTICA", text: "ESTADÍSTICA" },
  { value: "AUDIO Y EVENTOS", text: "AUDIO Y EVENTOS" },
  { value: "SOPORTE TÉCNICO (JORNADA)", text: "SOPORTE TÉCNICO (JORNADA)" },
  { value: "ARCHIVO CLÍNICO", text: "ARCHIVO CLÍNICO" },
  { value: "PROYECTOS Y SISTEMAS", text: "PROYECTOS Y SISTEMAS" },
  { value: "AUXILIAR DE INFORMÁTICA", text: "AUXILIAR DE INFORMÁTICA" },
  { value: "SEGURIDAD INFORMÁTICA", text: "SEGURIDAD INFORMÁTICA" },
  {
    value: "SOPORTE TÉCNICO ( VESPERTINO )",
    text: "SOPORTE TÉCNICO ( VESPERTINO )",
  },
  { value: "SOPORTE TÉCNICO", text: "SOPORTE TÉCNICO" },
  {
    value: "ASISTENTE DE LA DIRECCIÓN OPERATIVA (VESPERTINO)",
    text: "ASISTENTE DE LA DIRECCIÓN OPERATIVA (VESPERTINO)",
  },
  {
    value: "ASISTENTE DE LA DIRECCIÓN DE SERVICIOS AUXILIARES Y DE DIAGNÓSTICO",
    text: "ASISTENTE DE LA DIRECCIÓN DE SERVICIOS AUXILIARES Y DE DIAGNÓSTICO",
  },
  { value: "ASISTENTE DE PATOLOGÍA", text: "ASISTENTE DE PATOLOGÍA" },
  {
    value: "ASISTENTE DE LA COORDINACIÓN DE HEMATO-ONCOLOGÍA",
    text: "ASISTENTE DE LA COORDINACIÓN DE HEMATO-ONCOLOGÍA",
  },
  {
    value: "ASISTENTE DE LA COORDINACIÓN DE FINANZAS Y CONTABILIDAD",
    text: "ASISTENTE DE LA COORDINACIÓN DE FINANZAS Y CONTABILIDAD",
  },
  {
    value: "ASISTENTE DE LA COORDINACIÓN DE RECURSOS MATERIALES",
    text: "ASISTENTE DE LA COORDINACIÓN DE RECURSOS MATERIALES",
  },
  {
    value: "ASISTENTE DE LA SUBDIRECCIÓN DE TRABAJO SOCIAL",
    text: "ASISTENTE DE LA SUBDIRECCIÓN DE TRABAJO SOCIAL",
  },
  {
    value: "ASISTENTE DE LA COORDINACIÓN DE FINANZAS Y CONTABILIDAD",
    text: "ASISTENTE DE LA COORDINACIÓN DE FINANZAS Y CONTABILIDAD",
  },
  {
    value: "ASISTENTE DE LA COORDINACIÓN DE FINANZAS Y CONTABILIDAD",
    text: "ASISTENTE DE LA COORDINACIÓN DE FINANZAS Y CONTABILIDAD",
  },
  {
    value: "ASISTENTE DE LA COORDINACIÓN DE ADMINISTRACIÓN DE PERSONAL",
    text: "ASISTENTE DE LA COORDINACIÓN DE ADMINISTRACIÓN DE PERSONAL",
  },
  { value: "TRABAJO SOCIAL ONCOLOGIA", text: "TRABAJO SOCIAL ONCOLOGIA" },
  { value: "TRABAJO SOCIAL PEDIATRIA", text: "TRABAJO SOCIAL PEDIATRIA" },
  {
    value: "TRABAJO SOCIAL CONSULTA EXTERNA",
    text: "TRABAJO SOCIAL CONSULTA EXTERNA",
  },
  {
    value: "TRABAJO SOCIAL DE HOSPITALIZACION CIRUGIA",
    text: "TRABAJO SOCIAL DE HOSPITALIZACION CIRUGIA",
  },
  {
    value: "TRABAJO SOCIAL CIRUGIA PROGRAMADA",
    text: "TRABAJO SOCIAL CIRUGIA PROGRAMADA",
  },
  { value: "TRABAJO SOCIAL DE URGENCIAS", text: "TRABAJO SOCIAL DE URGENCIAS" },
  { value: "TRABAJO SOCIAL UCIN / UTIP", text: "TRABAJO SOCIAL UCIN / UTIP" },
  {
    value: "ASISTENTE DE LA SUBDIRECCIÓN DE TRABAJO SOCIAL",
    text: "ASISTENTE DE LA SUBDIRECCIÓN DE TRABAJO SOCIAL",
  },
];

export const LISTA_EXTENSION = [
  { value: "4260", text: "4260" },
  { value: "4280", text: "4280" },
  { value: "4030", text: "4030" },
  { value: "4520", text: "4520" },
  { value: "4560", text: "4560" },
  { value: "2160", text: "2160" },
  { value: "4540", text: "4540" },
  { value: "4530", text: "4530" },
  { value: "2680", text: "2680" },
  { value: "4060", text: "4060" },
  { value: "1200", text: "1200" },
  { value: "7210", text: "7210" },
  { value: "8050", text: "8050" },
  { value: "2060", text: "2060" },
  { value: "4010", text: "4010" },
  { value: "4620", text: "4620" },
  { value: "3290", text: "3290" },
  { value: "1290", text: "1290" },
  { value: "2180", text: "2180" },
  { value: "2190", text: "2190" },
  { value: "5040", text: "5040" },
  { value: "2240", text: "2240" },
  { value: "3310", text: "3310" },
  { value: "6140", text: "6140" },
  { value: "8020", text: "8020" },
];

// Combine both lists into a single listexport 
export const LISTA_COMBINADA = [
  { value: "Coordinadora de Área de Administración de Personal - 1300", text: "Coordinadora de Área de Administración de Personal - 1300" },
  { value: "CONMUTADOR (JORNADA) - 4580", text: "CONMUTADOR (JORNADA) - 4580" },
  { value: "RECLUTAMIENTO Y SELECCION DE PERSONAL - 1270", text: "RECLUTAMIENTO Y SELECCION DE PERSONAL - 1270" },
  { value: "Asistente de la Coordinación de Área de Administración de Personal - 1290", text: "Asistente de la Coordinación de Área de Administración de Personal - 1290" },
  { value: "CONTROL OPERATIVO - 4570", text: "CONTROL OPERATIVO - 4570" },
  { value: "Jefatura de Área de Nómina 'A' - 3220", text: "Jefatura de Área de Nómina 'A' - 3220" },
  { value: "APOYO ADMINISTRATIVO - 1330", text: "APOYO ADMINISTRATIVO - 1330" },
  { value: "NÓMINA - 1310", text: "NÓMINA - 1310" },
  { value: "Asistente de la Dirección de Unidad de Calidad y Mejora Continua - 2470", text: "Asistente de la Dirección de Unidad de Calidad y Mejora Continua - 2470" },
  { value: "Encargada de Despacho de la Dirección de Unidad de Calidad y Mejora Continua - 4240", text: "Encargada de Despacho de la Dirección de Unidad de Calidad y Mejora Continua - 4240" },
  { value: "JEFATURA DE CEYE - 8070", text: "JEFATURA DE CEYE - 8070" },
  { value: "CEYE ÁREA DE TRABAJO - 8060", text: "CEYE ÁREA DE TRABAJO - 8060" },
  { value: "CEYE ENTREGA DE MATERIAL - 8120", text: "CEYE ENTREGA DE MATERIAL - 8120" },
  { value: "QUIRÓFANO 1 - 8310", text: "QUIRÓFANO 1 - 8310" },
  { value: "QUIRÓFANO 2 - 8320", text: "QUIRÓFANO 2 - 8320" },
  { value: "QUIRÓFANO 4 - 8340", text: "QUIRÓFANO 4 - 8340" },
  { value: "QUIRÓFANO 5 - 8350", text: "QUIRÓFANO 5 - 8350" },
  { value: "QUIRÓFANO 6 - 8360", text: "QUIRÓFANO 6 - 8360" },
  { value: "RECUPERACIÓN DE CIRUGÍA - 8210", text: "RECUPERACIÓN DE CIRUGÍA - 8210" },
  { value: "VESTIDOR DE CIRUJANOS (MUJERES) - 8140", text: "VESTIDOR DE CIRUJANOS (MUJERES) - 8140" },
  { value: "VESTIDOR DE CIRUJANOS (HOMBRES) - 8540", text: "VESTIDOR DE CIRUJANOS (HOMBRES) - 8540" },
  { value: "Asistente de la Dirección de Unidad de Cirugía y Anestesia - 6070", text: "Asistente de la Dirección de Unidad de Cirugía y Anestesia - 6070" },
  { value: "JEFATURA DE ANESTESIA - 8190", text: "JEFATURA DE ANESTESIA - 8190" },
  { value: "COMISARÍA - 4310", text: "COMISARÍA - 4310" },
  { value: "AUDITORES COMISARÍA - 4320", text: "AUDITORES COMISARÍA - 4320" },
  { value: "TALLERES DE MANTENIMIENTO - 8080", text: "TALLERES DE MANTENIMIENTO - 8080" },
  { value: "ALMACÉN DE MANTENIMIENTO - 8090", text: "ALMACÉN DE MANTENIMIENTO - 8090" },
  { value: "Asistente de la Coordinación de Área de Conservación y Mantenimiento de Infraestructura - 2370", text: "Asistente de la Coordinación de Área de Conservación y Mantenimiento de Infraestructura - 2370" },
  { value: "BIOMEDICA - 2050", text: "BIOMEDICA - 2050" },
  { value: "Jefe de Área de Mantenimiento y Conservación Ambiental - 8530", text: "Jefe de Área de Mantenimiento y Conservación Ambiental - 8530" },
  { value: "Encargado de Despacho de la Coordinación de Área de Conservación y Mantenimiento de Infraestructura - 2390", text: "Encargado de Despacho de la Coordinación de Área de Conservación y Mantenimiento de Infraestructura - 2390" },
  { value: "Encargado de la Dirección de Unidad de Consulta Externa - 8150", text: "Encargado de la Dirección de Unidad de Consulta Externa - 8150" },
  { value: "RECEPCIÓN DE CONSULTA EXTERNA 1 - 2420", text: "RECEPCIÓN DE CONSULTA EXTERNA 1 - 2420" },
  { value: "RECEPCIÓN DE CONSULTA EXTERNA 2 - 2450", text: "RECEPCIÓN DE CONSULTA EXTERNA 2 - 2450" },
  { value: "CONSULTORIO 01 - PEDIATRÍA - 2410", text: "CONSULTORIO 01 - PEDIATRÍA - 2410" },
  { value: "CONSULTORIO 02 - ORTOPEDIA - 2720", text: "CONSULTORIO 02 - ORTOPEDIA - 2720" },
  { value: "CONSULTORIO 03 - PEDIATRÍA - 2730", text: "CONSULTORIO 03 - PEDIATRÍA - 2730" },
  { value: "CONSULTORIO 04 - DERMATOLOGÍA - 2740", text: "CONSULTORIO 04 - DERMATOLOGÍA - 2740" },
  { value: "CONSULTORIO 05 - GASTROENTEROLOGÍA - 2750", text: "CONSULTORIO 05 - GASTROENTEROLOGÍA - 2750" },
  { value: "CONSULTORIO 06 - GASTROENTEROLOGÍA - 2760", text: "CONSULTORIO 06 - GASTROENTEROLOGÍA - 2760" },
  { value: "CONSULTORIO 07 - TERAPIA DEL LENGUAJE - 2770", text: "CONSULTORIO 07 - TERAPIA DEL LENGUAJE - 2770" },
  { value: "CONSULTORIO 08 - AUDIOLOGÍA - 2780", text: "CONSULTORIO 08 - AUDIOLOGÍA - 2780" },
  { value: "CONSULTORIO 09 - ENDOCRINOLOGÍA - 2830", text: "CONSULTORIO 09 - ENDOCRINOLOGÍA - 2830" },
  { value: "CONSULTORIO 10 - INFECTO LOGIA - 2840", text: "CONSULTORIO 10 - INFECTO LOGIA - 2840" },
  { value: "CONSULTORIO 11 - ALERGOLOGÍA 1 - 2850", text: "CONSULTORIO 11 - ALERGOLOGÍA 1 - 2850" },
  { value: "CONSULTORIO 12 - ALERGOLOGÍA 2 - 2870", text: "CONSULTORIO 12 - ALERGOLOGÍA 2 - 2870" },
  { value: "CONSULTORIO 13 - REHABILITATION - 2810", text: "CONSULTORIO 13 - REHABILITATION - 2810" },
  { value: "CONSULTORIO 14 - PEDIATRÍA Y CLÍNICA DE VIH - 2560", text: "CONSULTORIO 14 - PEDIATRÍA Y CLÍNICA DE VIH - 2560" },
  { value: "CONSULTORIO 15 - NEUROCIRUGÍA - 2570", text: "CONSULTORIO 15 - NEUROCIRUGÍA - 2570" },
  { value: "CONSULTORIO 16 - OFTALMOLOGÍA - 2580", text: "CONSULTORIO 16 - OFTALMOLOGÍA - 2580" },
  { value: "CONSULTORIO 17 - REUMATOLOGÍA Y UROLOGÍA - 2590", text: "CONSULTORIO 17 - REUMATOLOGÍA Y UROLOGÍA - 2590" },
  { value: "CONSULTORIO 18 - CARDIOLOGÍA - 2600", text: "CONSULTORIO 18 - CARDIOLOGÍA - 2600" },
  { value: "CONSULTORIO 19 - CIRUGÍA PEDIÁTRICA - 2610", text: "CONSULTORIO 19 - CIRUGÍA PEDIÁTRICA - 2610" },
  { value: "CONSULTORIO 20 - INFECTO LOGIA - 2620", text: "CONSULTORIO 20 - INFECTO LOGIA - 2620" },
  { value: "CONSULTORIO 21 - NEONATOLOGÍA - 2630", text: "CONSULTORIO 21 - NEONATOLOGÍA - 2630" },
  { value: "CONSULTORIO 22 - NEUROPEDIATRIA - 2640", text: "CONSULTORIO 22 - NEUROPEDIATRIA - 2640" },
  { value: "CONSULTORIO 23 - REHABILITATION - 2650", text: "CONSULTORIO 23 - REHABILITATION - 2650" },
  { value: "CONSULTORIO 24 - OTORRINO_LARINGÓLOGÍA - 2660", text: "CONSULTORIO 24 - OTORRINO_LARINGÓLOGÍA - 2660" },
  { value: "CONSULTORIO 25 - PSIQUIATRÍA - 2670", text: "CONSULTORIO 25 - PSIQUIATRÍA - 2670" },
  { value: "CONSULTORIO 26 - NEUROPSICOLOGÍA - 2690", text: "CONSULTORIO 26 - NEUROPSICOLOGÍA - 2690" },
  { value: "CONSULTORIO 27 - PSICOLOGÍA - 2700", text: "CONSULTORIO 27 - PSICOLOGÍA - 2700" },
  { value: "OFICINA DE MAXILOFACIAL - 2540", text: "OFICINA DE MAXILOFACIAL - 2540" },
  { value: "CONSULTORIO 28 - ORTODONCIA - 2530", text: "CONSULTORIO 28 - ORTODONCIA - 2530" },
  { value: "CONSULTORIO 28 - CIRUGÍA MAXILOFACIAL - 2550", text: "CONSULTORIO 28 - CIRUGÍA MAXILOFACIAL - 2550" },
  { value: "CONSULTORIO 28 - CLÍNICA MAXILOFACIAL - 2520", text: "CONSULTORIO 28 - CLÍNICA MAXILOFACIAL - 2520" },
  { value: "CONSULTORIO 28 - ODONTOPEDIATRIA - 2510", text: "CONSULTORIO 28 - ODONTOPEDIATRIA - 2510" },
  { value: "ELECTROFISIOLOGIA CE - 2500", text: "ELECTROFISIOLOGIA CE - 2500" },
  { value: "CONSULTORIO 29 - POTENCIALES AUDITIVOS - 2490", text: "CONSULTORIO 29 - POTENCIALES AUDITIVOS - 2490" },
  { value: "CONSULTORIO 31 - NUTRICIÓN 2 - 2110", text: "CONSULTORIO 31 - NUTRICIÓN 2 - 2110" },
  { value: "CONSULTORIO HEMATOLOGÍA 1 - 2040", text: "CONSULTORIO HEMATOLOGÍA 1 - 2040" },
  { value: "CONSULTORIO HEMATOLOGÍA 2 - 2030", text: "CONSULTORIO HEMATOLOGÍA 2 - 2030" },
  { value: "CONSULTORIO ONCOLOGÍA 1 - 2010", text: "CONSULTORIO ONCOLOGÍA 1 - 2010" },
  { value: "CONSULTORIO ONCOLOGÍA 2 - 2020", text: "CONSULTORIO ONCOLOGÍA 2 - 2020" },
  { value: "CLÍNICA DEL DOLOR - 2120", text: "CLÍNICA DEL DOLOR - 2120" },
  { value: "TANATOLOGÍA - 2150", text: "TANATOLOGÍA - 2150" },
  { value: "Asistente de la Dirección de Unidad de Consulta Externa - 2400", text: "Asistente de la Dirección de Unidad de Consulta Externa - 2400" },
  { value: "AGENDAS CONSULTA EXTERNA - 1090", text: "AGENDAS CONSULTA EXTERNA - 1090" },
  { value: "CONSULTORIO 31 - NUTRICIÓN - 2140", text: "CONSULTORIO 31 - NUTRICIÓN - 2140" },
  { value: "PSICOONCOLOGIA - 2130", text: "PSICOONCOLOGIA - 2130" },
  { value: "CLÍNICA DE ESTOMAS - 2890", text: "CLÍNICA DE ESTOMAS - 2890" },
  { value: "FISCALÍA - 3000", text: "FISCALÍA - 3000" },
  { value: "CAFETERÍA - 2320", text: "CAFETERÍA - 2320" },
  { value: "OFICINA DEL COMEDOR - 1280", text: "OFICINA DEL COMEDOR - 1280" },
  { value: "COMEDOR - 8000", text: "COMEDOR - 8000" },
  { value: "ESCUELITA - 7040", text: "ESCUELITA - 7040" },
  { value: "ASISTENTE DE LA DIRECCIÓN OPERATIVA (VESPERTINO) - 1200", text: "ASISTENTE DE LA DIRECCIÓN OPERATIVA (VESPERTINO) - 1200" },
  { value: "DIRECCIÓN OPERATIVA (DOMINICAL) - 2430", text: "DIRECCIÓN OPERATIVA (DOMINICAL) - 2430" },
  { value: "DIRECCIÓN OPERATIVA (NOCTURNO) - 2430", text: "DIRECCIÓN OPERATIVA (NOCTURNO) - 2430" },
  { value: "DIRECCIÓN OPERATIVA (SABATINO) - 2430", text: "DIRECCIÓN OPERATIVA (SABATINO) - 2430" },
  { value: "Director de Unidad de Cirugía y Anestesia - 2430", text: "Director de Unidad de Cirugía y Anestesia - 2430" },
  { value: "DIRECCIÓN OPERATIVA (VESPERTINO) - 2430", text: "DIRECCIÓN OPERATIVA (VESPERTINO) - 2430" },
  { value: "NEBULIZACIÓN - 4070", text: "NEBULIZACIÓN - 4070" },
  { value: "EPIDEMIOLOGÍA - 2260", text: "EPIDEMIOLOGÍA - 2260" },
  { value: "INHALOTERAPIA - 3060", text: "INHALOTERAPIA - 3060" },
  { value: "CENTRAL DE ENFERMERAS DE ONCOLOGÍA - 2090", text: "CENTRAL DE ENFERMERAS DE ONCOLOGÍA - 2090" },
  { value: "SOMATOMETRIA CONSULTA EXTERNA - 2480", text: "SOMATOMETRIA CONSULTA EXTERNA - 2480" },
  { value: "CENTRAL DE ENFERMERAS HOSPITALIZACIÓN ONCOLOGÍA (ÁREA 1) - 1250", text: "CENTRAL DE ENFERMERAS HOSPITALIZACIÓN ONCOLOGÍA (ÁREA 1) - 1250" },
  { value: "CENTRAL DE ENFERMERAS HOSPITALIZACIÓN ONCOLOGÍA (ÁREA 2) - 3030", text: "CENTRAL DE ENFERMERAS HOSPITALIZACIÓN ONCOLOGÍA (ÁREA 2) - 3030" },
  { value: "CENTRAL DE ENFERMERAS HOSPITALIZACIÓN ONCOLOGÍA (ÁREA 3) - 4080", text: "CENTRAL DE ENFERMERAS HOSPITALIZACIÓN ONCOLOGÍA (ÁREA 3) - 4080" },
  { value: "CENTRAL DE ENFERMERAS HOSPITALIZACIÓN PEDIATRÍA - 3070", text: "CENTRAL DE ENFERMERAS HOSPITALIZACIÓN PEDIATRÍA - 3070" },
  { value: "Encargado de Despacho de la Subdirección de Unidad de Enfermería - 1150", text: "Encargado de Despacho de la Subdirección de Unidad de Enfermería - 1150" },
  { value: "OFICINA DE ENFERMERAS UTIP - 8630", text: "OFICINA DE ENFERMERAS UTIP - 8630" },
  { value: "VACUNAS - 2860", text: "VACUNAS - 2860" },
  { value: "CENTRAL DE ENFERMERAS HOSPITALIZACIÓN CIRUGÍA - 3010", text: "CENTRAL DE ENFERMERAS HOSPITALIZACIÓN CIRUGÍA - 3010" },
  { value: "SOMATOMETRIA DE URGENCIAS - 7120", text: "SOMATOMETRIA DE URGENCIAS - 7120" },
  { value: "CENTRAL ENFERMERAS URGENCIAS (ÁREA CRITICA) - 7090", text: "CENTRAL ENFERMERAS URGENCIAS (ÁREA CRITICA) - 7090" },
  { value: "CENTRAL DE ENFERMERAS URGENCIAS (ÁREA NO CRITICA) - 6050", text: "CENTRAL DE ENFERMERAS URGENCIAS (ÁREA NO CRITICA) - 6050" },
  { value: "CENTRAL DE ENFERMERAS UCIN (PRIMERA SECCIÓN) - 8300", text: "CENTRAL DE ENFERMERAS UCIN (PRIMERA SECCIÓN) - 8300" },
  { value: "CENTRAL DE ENFERMERAS UCIN (SEGUNDA SECCIÓN) - 8550", text: "CENTRAL DE ENFERMERAS UCIN (SEGUNDA SECCIÓN) - 8550" },
  { value: "CENTRAL DE ENFERMERIA UTIP 1 - 8590", text: "CENTRAL DE ENFERMERIA UTIP 1 - 8590" },
  { value: "CENTRAL DE ENFERMERIA UTIP 2 - 8600", text: "CENTRAL DE ENFERMERIA UTIP 2 - 8600" },
  { value: "CENTRAL DE ENFERMERAS UTIP 1 (ÁREA DESOCUPADA) - 8620", text: "CENTRAL DE ENFERMERAS UTIP 1 (ÁREA DESOCUPADA) - 8620" },
  { value: "CENTRAL DE ENFERMERAS DE CIRUGIA AMBULATORIA - 8110", text: "CENTRAL DE ENFERMERAS DE CIRUGIA AMBULATORIA - 8110" },
  { value: "OFICINA VACUNAS - 5010", text: "OFICINA VACUNAS - 5010" },
  { value: "Asistente de la Subdirección de Unidad de Enfermería - 1160", text: "Asistente de la Subdirección de Unidad de Enfermería - 1160" },
  { value: "NOSOCOMIALES - 2260", text: "NOSOCOMIALES - 2260" },
  { value: "Coordinadora de Enseñanza de Enfermería - 1180", text: "Coordinadora de Enseñanza de Enfermería - 1180" },
  { value: "Asistente de la Coordinación de Enseñanza de Enfermería - 1170", text: "Asistente de la Coordinación de Enseñanza de Enfermería - 1170" },
  { value: "Encargada de Despacho de la Dirección de Unidad de Enseñanza e Investigación - 2380", text: "Encargada de Despacho de la Dirección de Unidad de Enseñanza e Investigación - 2380" },
  { value: "UNIDAD INVESTIGACIÓN UAEM - 5060", text: "UNIDAD INVESTIGACIÓN UAEM - 5060" },
  { value: "ÁREA RESIDENTES HOMBRES - 3090", text: "ÁREA RESIDENTES HOMBRES - 3090" },
  { value: "ÁREA RESIDENTES MUJERES - 3100", text: "ÁREA RESIDENTES MUJERES - 3100" },
  { value: "Asistente de la Dirección de Unidad de Enseñanza e Investigación - 2310", text: "Asistente de la Dirección de Unidad de Enseñanza e Investigación - 2310" },
  { value: "COORDINACIÓN DE INVESTIGACIÓN DE LA DUEI - 2340", text: "COORDINACIÓN DE INVESTIGACIÓN DE LA DUEI - 2340" },
  { value: "Coordinadora de Área de Finanzas y Contabilidad - 4050", text: "Coordinadora de Área de Finanzas y Contabilidad - 4050" },
  { value: "CAJA DE URGENCIAS - 6130", text: "CAJA DE URGENCIAS - 6130" },
  { value: "CAJA CONSULTA EXTERNA - 2440", text: "CAJA CONSULTA EXTERNA - 2440" },
  { value: "CAJA GENERAL - 5030", text: "CAJA GENERAL - 5030" },
  { value: "Asistente de la Coordinación de Área de Finanzas y Contabilidad - 4010", text: "Asistente de la Coordinación de Área de Finanzas y Contabilidad - 4010" },
  { value: "Jefe de Área de Presupuesto - 4020", text: "Jefe de Área de Presupuesto - 4020" },
  { value: "FINANZAS Y CONTABILIDAD - 4010", text: "FINANZAS Y CONTABILIDAD - 4010" },
  { value: "JEFATURA DE ÁREA DE PRESUPUESTO - 4020", text: "JEFATURA DE ÁREA DE PRESUPUESTO - 4020" },
  { value: "Encargado de Despacho de la Jefatura de Área de Contabilidad - 4040", text: "Encargado de Despacho de la Jefatura de Área de Contabilidad - 4040" },
  { value: "ÁREA MÉDICA DE HOSPITALIZACIÓN - CIRUGÍA - 8230", text: "ÁREA MÉDICA DE HOSPITALIZACIÓN - CIRUGÍA - 8230" },
  { value: "Directora de Unidad de Hospitalización - 8160", text: "Directora de Unidad de Hospitalización - 8160" },
  { value: "SALA DE JUNTAS HOSPITALIZACIÓN - 3130", text: "SALA DE JUNTAS HOSPITALIZACIÓN - 3130" },
  { value: "ÁREA MÉDICA DE HOSPITALIZACIÓN - 3160", text: "ÁREA MÉDICA DE HOSPITALIZACIÓN - 3160" },
  { value: "Asistente de la Coordinación de Hemato-Oncología - 2060", text: "Asistente de la Coordinación de Hemato-Oncología - 2060" },
  { value: "Asistente de la Dirección de Unidad de Hospitalización - 2820", text: "Asistente de la Dirección de Unidad de Hospitalización - 2820" },
  { value: "MEDICINA PREVENCIÓN Y CONTROL, Y CIAAS - 3280", text: "MEDICINA PREVENCIÓN Y CONTROL, Y CIAAS - 3280" },
  { value: "SUBDIRECCIÓN DE UNIDAD DE LABORATORIO - 1240", text: "SUBDIRECCIÓN DE UNIDAD DE LABORATORIO - 1240" },
  { value: "HEMATOLOGÍA - 5070", text: "HEMATOLOGÍA - 5070" },
  { value: "MICROBIOLOGIA - 3040", text: "MICROBIOLOGIA - 3040" },
  { value: "QUÍMICA CLÍNICA - 1350", text: "QUÍMICA CLÍNICA - 1350" },
  { value: "SERVICIO DE TRANSFUSION - 5050", text: "SERVICIO DE TRANSFUSION - 5050" },
  { value: "URO ANALISIS Y PARASITOLOGIA - 3080", text: "URO ANALISIS Y PARASITOLOGIA - 3080" },
  { value: "TRANSFUSIÓN - 1370", text: "TRANSFUSIÓN - 1370" },
  { value: "GENETICA - 5080", text: "GENETICA - 5080" },
  { value: "RECEPCIÓN LABORATORIO - 1140", text: "RECEPCIÓN LABORATORIO - 1140" },
  { value: "RECEPCIÓN LABORATORIO (VESPERTINO) - 8520", text: "RECEPCIÓN LABORATORIO (VESPERTINO) - 8520" },
  { value: "ÁREA MÉDICA DE UCIN - 6020", text: "ÁREA MÉDICA DE UCIN - 6020" },
  { value: "ÁREA MÉDICA DE URGENCIAS - 7080", text: "ÁREA MÉDICA DE URGENCIAS - 7080" },
  { value: "CONSULTORIO 1 DE URGENCIAS - 7110", text: "CONSULTORIO 1 DE URGENCIAS - 7110" },
  { value: "CONSULTORIO 2 DE URGENCIAS - 7140", text: "CONSULTORIO 2 DE URGENCIAS - 7140" },
  { value: "CONSULTORIO 3 DE URGENCIAS - 8560", text: "CONSULTORIO 3 DE URGENCIAS - 8560" },
  { value: "Asistente de la Dirección de Unidad de Medicina Crítica y Urgencias - 8570", text: "Asistente de la Dirección de Unidad de Medicina Crítica y Urgencias - 8570" },
  { value: "JEFE OFICINA CALIDAD - 5120", text: "JEFE OFICINA CALIDAD - 5120" },
  { value: "Encargada de Despacho de Enlace de Programas Federales (IMSS-BIENESTAR) - 5210", text: "Encargada de Despacho de Enlace de Programas Federales (IMSS-BIENESTAR) - 5210" },
  { value: "OFICINA DE MÉDICOS GESTORES - 4000", text: "OFICINA DE MÉDICOS GESTORES - 4000" },
  { value: "MÓDULO IMSS-BIENESTAR - 5220", text: "MÓDULO IMSS-BIENESTAR - 5220" },
  { value: "Asistente de la Coordinación de Programas Federales (IMSS-BIENESTAR) - 1320", text: "Asistente de la Coordinación de Programas Federales (IMSS-BIENESTAR) - 1320" },
  { value: "FARMACIA DE PROGRAMAS FEDERALES (INSABI) - 2250", text: "FARMACIA DE PROGRAMAS FEDERALES (INSABI) - 2250" },
  { value: "COMPRAS - 2290", text: "COMPRAS - 2290" },
  { value: "VENTANILLA DE ALMACÉN - 4450", text: "VENTANILLA DE ALMACÉN - 4450" },
  { value: "FARMACIA GENERAL (VENTANILLA) - 2270", text: "FARMACIA GENERAL (VENTANILLA) - 2270" },
  { value: "OFICINA DE DOSIS UNITARIAS - 2200", text: "OFICINA DE DOSIS UNITARIAS - 2200" },
  { value: "ALMACÉN DE MEDICAMENTOS - 2220", text: "ALMACÉN DE MEDICAMENTOS - 2220" },
  { value: "FARMACOTECNIA - 2210", text: "FARMACOTECNIA - 2210" },
  { value: "BANCO DE LECHE - 2230", text: "BANCO DE LECHE - 2230" },
  { value: "Jefe de Área de Almacén - 4470", text: "Jefe de Área de Almacén - 4470" },
  { value: "COMPRAS - 4610", text: "COMPRAS - 4610" },
  { value: "Jefe de Área de Adquisiciones - 8640", text: "Jefe de Área de Adquisiciones - 8640" },
  { value: "Coordinador de Área de Recursos Materiales y Control Patrimonial - 2100", text: "Coordinador de Área de Recursos Materiales y Control Patrimonial - 2100" },
  { value: "CONTROL PATRIMONIAL - 4600", text: "CONTROL PATRIMONIAL - 4600" },
  { value: "Jefe de Área de Farmacia y Responsable Sanitario - 2280", text: "Jefe de Área de Farmacia y Responsable Sanitario - 2280" },
  { value: "Asistente de la Coordinación de Área de Recursos Materiales y Control Patrimonial - 4620", text: "Asistente de la Coordinación de Área de Recursos Materiales y Control Patrimonial - 4620" },
  { value: "OFICIALIA DE PARTES COMUNES - 8580", text: "OFICIALIA DE PARTES COMUNES - 8580" },
  { value: "TOMOGRAFÍA - 7050", text: "TOMOGRAFÍA - 7050" },
  { value: "FLUOROSCOPIA 1 - 4210", text: "FLUOROSCOPIA 1 - 4210" },
  { value: "FLUOROSCOPIA 2 - 4230", text: "FLUOROSCOPIA 2 - 4230" },
  { value: "SALA RAYOS X - 7150", text: "SALA RAYOS X - 7150" },
  { value: "MICROSCOPIO ELECTRÓNICO - 8030", text: "MICROSCOPIO ELECTRÓNICO - 8030" },
  { value: "LABORATORIO DE CITOLOGÍA - 8220", text: "LABORATORIO DE CITOLOGÍA - 8220" },
  { value: "Asistente de Patología - 8050", text: "Asistente de Patología - 8050" },
  { value: "SALA DE INTERPRETACIÓN - 7100", text: "SALA DE INTERPRETACIÓN - 7100" },
  { value: "Encargado de Despacho de la Unidad de Servicios Auxiliares y de Diagnóstico - 8200", text: "Encargado de Despacho de la Unidad de Servicios Auxiliares y de Diagnóstico - 8200" },
  { value: "INMUNODIAGNOSTICO - 8040", text: "INMUNODIAGNOSTICO - 8040" },
  { value: "INMUNOFLORECENCIA (VESPERTINO) - 4590", text: "INMUNOFLORECENCIA (VESPERTINO) - 4590" },
  { value: "RECEPCIÓN DE IMAGENOLOGIA - 7210", text: "RECEPCIÓN DE IMAGENOLOGIA - 7210" },
  { value: "Asistente de la Dirección de Unidad de Servicios Auxiliares y de Diagnóstico - 2300", text: "Asistente de la Dirección de Unidad de Servicios Auxiliares y de Diagnóstico - 2300" },
  { value: "Coordinador de Área de Servicios Generales - 1050", text: "Coordinador de Área de Servicios Generales - 1050" },
  { value: "OFICINA DE SERVICIOS GENERALES - 7020", text: "OFICINA DE SERVICIOS GENERALES - 7020" },
  { value: "LAVANDERIA - 8290", text: "LAVANDERIA - 8290" },
  { value: "VIGILANCIA DE CONTROL OPERATIVO - 8180", text: "VIGILANCIA DE CONTROL OPERATIVO - 8180" },
  { value: "RECEPCIÓN DE CIRUGIA AMBULATORIA - 6000", text: "RECEPCIÓN DE CIRUGIA AMBULATORIA - 6000" },
  { value: "EMERGENCIAS - 8170", text: "EMERGENCIAS - 8170" },
  { value: "VIGILANCIA URGENCIAS - 2350", text: "VIGILANCIA URGENCIAS - 2350" },
  { value: "VIGILANCIA LOBBY - 5020", text: "VIGILANCIA LOBBY - 5020" },
  { value: "VIGILANCIA HOSPITALIZACIÓN - 2800", text: "VIGILANCIA HOSPITALIZACIÓN - 2800" },
  { value: "Asistente de la Coordinación de Área de Servicios Generales - 2800", text: "Asistente de la Coordinación de Área de Servicios Generales - 2800" },
  { value: "SERVICIOS GENERALES - 2900", text: "SERVICIOS GENERALES - 2900" },
  { value: "Encargada de Despacho de la Coordinación de Área de Servicios Jurídicos - 1120", text: "Encargada de Despacho de la Coordinación de Área de Servicios Jurídicos - 1120" },
  { value: "Jefe de Área de Protección Jurídico Infantil - 1100", text: "Jefe de Área de Protección Jurídico Infantil - 1100" },
  { value: "Auxiliar Jurídico - 1080", text: "Auxiliar Jurídico - 1080" },
  { value: "Asistente de la Coordinación de Área de Servicios Jurídicos - 1130", text: "Asistente de la Coordinación de Área de Servicios Jurídicos - 1130" },
  { value: "Auxiliar Jurídico - 1210", text: "Auxiliar Jurídico - 1210" },
  { value: "REPRESENTANTE SINDICAL - 5130", text: "REPRESENTANTE SINDICAL - 5130" },
  { value: "TESORERIA SINDICAL - 5110", text: "TESORERIA SINDICAL - 5110" },
  { value: "Subdirectora de Unidad de Seguridad del Paciente - 5120", text: "Subdirectora de Unidad de Seguridad del Paciente - 5120" },
  { value: "Subdirectora de Unidad de Seguridad Hospitalaria - 4240", text: "Subdirectora de Unidad de Seguridad Hospitalaria - 4240" },
  { value: "Asistente de la Supervisión de Enfermería - 8130", text: "Asistente de la Supervisión de Enfermería - 8130" },
  { value: "SUPERVISIÓN DE ENFERMERÍA - 7130", text: "SUPERVISIÓN DE ENFERMERÍA - 7130" },
  { value: "SUPERVISIÓN DE ENFERMERÍA - 7230", text: "SUPERVISIÓN DE ENFERMERÍA - 7230" },
  { value: "COORDINACIÓN DE ÁREA DE TECNOLOGÍAS DE LA INFORMACIÓN - 4260", text: "COORDINACIÓN DE ÁREA DE TECNOLOGÍAS DE LA INFORMACIÓN - 4260" },
  { value: "Subdirector de Área de Informática y Estadística - 4550", text: "Subdirector de Área de Informática y Estadística - 4550" },
  { value: "ESTADISTICA - 4560", text: "ESTADISTICA - 4560" },
  { value: "ARCHIVO CLINICO - 2160", text: "ARCHIVO CLINICO - 2160" },
  { value: "PROYECTOS Y SISTEMAS - 4540", text: "PROYECTOS Y SISTEMAS - 4540" },
  { value: "ARCHIVO CLINICO (VESPERTINO) - 2160", text: "ARCHIVO CLINICO (VESPERTINO) - 2160" },
  { value: "Asistente de la Coordinación de Área de Tecnologías de la Información - 4280", text: "Asistente de la Coordinación de Área de Tecnologías de la Información - 4280" },
  { value: "AUXILIAR DE INFORMATICA - 4530", text: "AUXILIAR DE INFORMATICA - 4530" },
  { value: "AUXILIAR DE INFORMATICA - 4030", text: "AUXILIAR DE INFORMATICA - 4030" },
  { value: "SEGURIDAD INFORMATICA - 2680", text: "SEGURIDAD INFORMATICA - 2680" },
  { value: "SOPORTE TECNICO (VESPERTINO) - 4060", text: "SOPORTE TECNICO (VESPERTINO) - 4060" },
  { value: "SOPORTE TECNICO - 4060", text: "SOPORTE TECNICO - 4060" },
  { value: "AUDIO Y EVENTOS - 4520", text: "AUDIO Y EVENTOS - 4520" },
  { value: "Encargado de Despacho de la Subdirección de Unidad de Trabajo Social - 1220", text: "Encargado de Despacho de la Subdirección de Unidad de Trabajo Social - 1220" },
  { value: "TRABAJO SOCIAL ONCOLOGIA - 2180", text: "TRABAJO SOCIAL ONCOLOGIA - 2180" },
  { value: "TRABAJO SOCIAL PEDIATRIA - 2190", text: "TRABAJO SOCIAL PEDIATRIA - 2190" },
  { value: "TRABAJO SOCIAL CONSULTA EXTERNA - 5040", text: "TRABAJO SOCIAL CONSULTA EXTERNA - 5040" },
  { value: "TRABAJO SOCIAL DE HOSPITALIZACION CIRUGIA - 2240", text: "TRABAJO SOCIAL DE HOSPITALIZACION CIRUGIA - 2240" },
  { value: "TRABAJO SOCIAL CIRUGIA PROGRAMADA - 3310", text: "TRABAJO SOCIAL CIRUGIA PROGRAMADA - 3310" },
  { value: "TRABAJO SOCIAL DE URGENCIAS - 6140", text: "TRABAJO SOCIAL DE URGENCIAS - 6140" },
  { value: "TRABAJO SOCIAL UCIN / UTIP - 8020", text: "TRABAJO SOCIAL UCIN / UTIP - 8020" },
  { value: "Asistente de la Subdirección de Unidad de Trabajo Social - 3290", text: "Asistente de la Subdirección de Unidad de Trabajo Social - 3290" },
  { value: "PRESIDENTA VOLUNTARIADO - 3050", text: "PRESIDENTA VOLUNTARIADO - 3050" },
  { value: "VOLUNTARIADO - 3020", text: "VOLUNTARIADO - 3020" },
  { value: "BANCO DE MEDICAMENTOS VOLUNTARIADO - 2170", text: "BANCO DE MEDICAMENTOS VOLUNTARIADO - 2170" }
];


export const LISTA_TIPO_EQUIPO = [
  [
    {
      value: "Tipo de equipo a revisar",
      hidden: true,
      text: "Tipo de equipo a revisar",
    },
    { value: "PC", text: "PC" },
    { value: "PC/Todo en uno", text: "PC/Todo en uno" },
    { value: "Laptop", text: "Laptop" },
    { value: "Terminal", text: "Terminal" },
    { value: "Impresora", text: "Impresora" },
    { value: "Escáner", text: "Escáner" },
    { value: "Multifuncional", text: "Multifuncional" },
    { value: "Otro", text: "Otro" },
  ],
];
